// GENERATED FILE -- do not hand-edit.
//
// Produced by tool/generate_play_by_play_phrases.py from
// play_by_play_phrases.toml. Edit the TOML (that's the GM's own
// hand-editable copy), then re-run the script to refresh this file:
//   python3 tool/generate_play_by_play_phrases.py

// 118 phrases across 19 categories.
const Map<String, List<String>> kPlayByPlayPhrases = {
  'tip_off': [
    '{player} wins the tip for {team}.',
    '{player} controls the opening tip, and {team} has the ball first.',
    '{player} out-jumps her opposite number to start it off for {team}.',
    '{player} taps it cleanly back to a teammate -- {team} ball to open the quarter.',
  ],
  'inbound_after_make': [
    '{player} inbounds the ball after the {opponent} score.',
    '{player} passes it in, looking to answer on offense.',
    'The ball is sent inbounds by {player}.',
    'After the {opponent} bucket, {player} bounces it in to {player2}.',
    '{player} takes the inbounds pass and starts {team} the other way.',
    '{player} steps out of bounds to put it back in play for {team}.',
    'Quick inbounds from {player} -- {team} wants to push the pace.',
    '{player} gets the ball in cleanly, {team} bringing it up.',
  ],
  'inbound_after_deadball': [
    '{player} inbounds after the whistle.',
    '{team} takes it out of bounds, {player} handling the pass-in.',
    '{player} restarts things for {team} after the stoppage.',
    'The referee hands it to {player} to put back in play.',
    '{player} checks it in for {team}.',
  ],
  'backcourt_bringup': [
    '{player} dribbles at the top, surveying the defense.',
    '{player} brings the ball up, calling out the set.',
    '{player} walks it up, in no hurry to attack.',
    '{player} controls the tempo, easing into the frontcourt.',
    '{player} pushes it up the floor, scanning for an opening.',
    '{player} settles the offense into its spacing.',
  ],
  'midcourt_advance': [
    '{player} swings it ahead to {player2} crossing half-court.',
    '{player} finds {player2} streaking into the frontcourt.',
    '{player} flips it up the sideline to {player2}.',
    '{player} advances the ball to {player2} near midcourt.',
    '{player} hits {player2} in stride past half-court.',
  ],
  'perimeter_no_name': [
    '{team} works it around the perimeter, probing for an opening.',
    '{team} swings the ball side to side, patient on offense.',
    '{team} is content to let the shot clock run, looking for a good look.',
    'The ball moves crisply around {team}\'s offense -- nothing there yet.',
    '{team} resets, running through their offense again.',
  ],
  'clock_milking': [
    '{player} slows it down, letting the clock bleed a little.',
    '{player} is in no rush -- {team} happy to eat the clock here.',
    '{player} holds it out top, content to wait.',
    '{player} controls the pace, {team} managing the clock.',
  ],
  'foul_no_ft': [
    '{player} picks up a foul away from the ball.',
    '{player} is whistled for a reach-in.',
    'A foul is called on {player} -- {team} not yet in the bonus.',
    '{player} gets tagged with a loose-ball foul.',
    '{player} gets a whistle for an over-the-back foul.',
  ],
  'twopt_make': [
    '{player} jukes her defender, steps left, and puts it up -- it\'s good for 2.',
    '{player} dribbles and takes a step, it\'s up, and it\'s good. 2 points.',
    '{player} fakes a shot, the defender bites, and she drains the mid-range for 2.',
    '{player} makes a nice jumpshot from just inside the perimeter for 2 points.',
    '{player} made that 2-pointer look easy!',
    '{player} drives and scores.',
    '{player} finishes strong through the contact.',
    '{player} rises for the pull-up and buries it.',
    '{player} spins baseline and finishes with the reverse.',
    '{player} pulls up from the elbow -- good.',
    '{player} gets to her spot and knocks it down.',
    '{player} slices through the lane for an easy bucket.',
    '{player} with the fadeaway... it\'s good.',
  ],
  'twopt_miss': [
    '{player}\'s shot rims out.',
    '{player}\'s jumper is off the mark.',
    '{player} can\'t connect, the ball caroms off the rim.',
    '{player}\'s attempt is short.',
    '{player} rushes the shot and misses everything.',
    '{player}\'s floater rolls off the front of the rim.',
    '{player} gets a good look but the shot won\'t fall.',
    '{player}\'s runner in the lane doesn\'t go.',
    'No good on {player}\'s attempt.',
    '{player}\'s shot clangs off the back iron.',
    '{player}\'s shot is looking good... nope, it bounces out.',
  ],
  'threept_make': [
    '{player} buries the three off the catch!',
    '{player} drills the corner three!',
    '{player} drains a three pointer!',
    '{player} lets it fly from deep -- and it\'s good!',
    '{player} steps back and buries it from downtown!',
    '{player} splashes one from way outside!',
    '{player} pulls up in transition and nails the triple!',
    '{player} finds nothing but net from beyond the arc!',
  ],
  'threept_miss': [
    '{player}\'s three rims out.',
    '{player}\'s deep ball is off target.',
    '{player} airballs the attempt from outside.',
    '{player}\'s three-point try doesn\'t have the distance.',
    '{player} can\'t connect from downtown.',
    '{player}\'s look from beyond the arc bounces away.',
    '{player}\'s three is long, no good.',
  ],
  'and_one': [
    '{player} scores through contact -- and-one!',
    '{player} finishes at the rim and draws the foul -- and-one chance!',
    '{player} powers it in with a body on her -- and-one!',
    '{player} absorbs the hit and still finishes -- and-one!',
    '{player} banks it home through contact -- and-one!',
    '{player} gets fouled through the shot, she\'s going back to the line for one more.',
  ],
  'free_throws': [
    '{player} steps to the line and hits both.',
    '{player} splits the pair at the line.',
    '{player} knocks down both free throws.',
    '{player} misses the first, makes the second at the line.',
    '{player} calmly sinks both from the stripe.',
  ],
  'putback': [
    '{player} cleans up the putback.',
    '{player} taps the offensive rebound back in.',
    '{player} follows her own miss and scores.',
    '{player} out-works everyone for the putback bucket.',
    '{player} grabs the offensive board and scores right back up.',
  ],
  'block': [
    '{player} swats the shot away!',
    '{player} rejects it at the rim!',
    '{player} sends the shot into the seats!',
    '{player} times the jump perfectly for the block!',
    '{player} denies it at the basket!',
  ],
  'steal': [
    '{player} tips the pass away!',
    '{player} jumps the passing lane for the steal!',
    '{player} picks the pocket clean!',
    '{player} reads the pass and comes away with it!',
    '{player} strips the ball loose!',
  ],
  'defensive_rebound': [
    '{player} pulls down the defensive rebound.',
    '{player} controls the boards for {team}.',
    '{player} cleans up the miss.',
    '{player} out-rebounds her matchup for the ball.',
    '{player} secures the rebound to end the possession.',
  ],
  'assist': [
    '{player} kicks it out to {player2} in the corner.',
    '{player} lobs a pass to {player2} on the perimeter.',
    '{player} finds {player2} cutting to the rim.',
    '{player} dishes it to {player2} for the open look.',
    '{player} threads a pass to {player2} in the paint.',
    '{player} swings it to {player2} on the wing.',
  ],
};
