/// Player-specific generation seed data (name pools moved to
/// `core/generation/name_pools.dart` once coach generation needed them
/// too). Flavor only — a mix of North American and international cities,
/// deliberately not the same list as the 20 league cities in `teams.md`.
const kHometowns = <String>[
  'Springfield, IL',
  'Albany, NY',
  'Richmond, VA',
  'Tulsa, OK',
  'Fresno, CA',
  'Spokane, WA',
  'Baton Rouge, LA',
  'Chattanooga, TN',
  'Winnipeg, MB',
  'Regina, SK',
  'Saskatoon, SK',
  'Victoria, BC',
  'Sydney, Australia',
  'Melbourne, Australia',
  'Paris, France',
  'Madrid, Spain',
  'Lagos, Nigeria',
  'Nairobi, Kenya',
  'Seoul, South Korea',
  'Manila, Philippines',
  'Zagreb, Croatia',
  'Belgrade, Serbia',
  'Toulouse, France',
  'Osaka, Japan',
  'Accra, Ghana',
  'Dakar, Senegal',
  'Bogota, Colombia',
  'Santiago, Chile',
  'Auckland, New Zealand',
  'Warsaw, Poland',
];
