/// Seed data for player generation. Purely invented — not drawn from any
/// real athlete roster — combined at random, so any resemblance to a real
/// person's full name is coincidental. Deliberately spans a range of
/// naming traditions to match the fictional world's international pipeline
/// (see `colleges.md`, `question.md` decision 22's note on international
/// rookies).
const kFirstNames = <String>[
  'Aaliyah',
  'Sofia',
  'Emma',
  'Zoe',
  'Maya',
  'Chidinma',
  'Fatima',
  'Noor',
  'Priya',
  'Ingrid',
  'Freya',
  'Elena',
  'Camila',
  'Valentina',
  'Amara',
  'Kayla',
  'Brianna',
  'Destiny',
  'Jasmine',
  'Alexis',
  'Morgan',
  'Taylor',
  'Jordan',
  'Sydney',
  'Madison',
  'Olivia',
  'Ava',
  'Isabella',
  'Mia',
  'Charlotte',
  'Layla',
  'Nadia',
  'Yuki',
  'Hana',
  'Mei',
  'Aiko',
  'Anh',
  'Linh',
  'Thandiwe',
  'Zanele',
  'Ngozi',
  'Adaeze',
  'Keisha',
  'Simone',
  'Renee',
  'Danielle',
];

const kLastNames = <String>[
  'Okafor',
  'Adeyemi',
  'Mensah',
  'Osei',
  'Diallo',
  'Traore',
  'Kone',
  'Nakamura',
  'Watanabe',
  'Kim',
  'Park',
  'Nguyen',
  'Tran',
  'Singh',
  'Patel',
  'Sharma',
  'Kaur',
  'Rodriguez',
  'Martinez',
  'Garcia',
  'Hernandez',
  'Lopez',
  'Silva',
  'Costa',
  'Almeida',
  'Petrov',
  'Ivanova',
  'Kowalski',
  'Nowak',
  'Novak',
  'Andersson',
  'Larsen',
  'Johansson',
  'Murphy',
  'Kelly',
  "O'Brien",
  'Clarke',
  'Bennett',
  'Coleman',
  'Sanders',
  'Reed',
  'Hayes',
];

/// Flavor only — a mix of North American and international cities,
/// deliberately not the same list as the 20 league cities in `teams.md`.
const kHometowns = <String>[
  'Springfield, IL',
  'Albany, NY',
  'Richmond, VA',
  'Tulsa, OK',
  'Fresno, CA',
  'Spokane, WA',
  'Baton Rouge, LA',
  'Chattanooga, TN',
  'Winnipeg, MB',
  'Regina, SK',
  'Saskatoon, SK',
  'Victoria, BC',
  'Sydney, Australia',
  'Melbourne, Australia',
  'Paris, France',
  'Madrid, Spain',
  'Lagos, Nigeria',
  'Nairobi, Kenya',
  'Seoul, South Korea',
  'Manila, Philippines',
  'Zagreb, Croatia',
  'Belgrade, Serbia',
  'Toulouse, France',
  'Osaka, Japan',
  'Accra, Ghana',
  'Dakar, Senegal',
  'Bogota, Colombia',
  'Santiago, Chile',
  'Auckland, New Zealand',
  'Warsaw, Poland',
];
