/// A human-checkable "did the last build actually reach my phone" stamp
/// (2026-08-21, a direct GM report: "Kinda makes me think the last build
/// didn't make it to my phone. I feel like that's happened a few times,
/// now... Maybe we could put a version number on the settings menu, and
/// I can check it after every build"). Regenerated by hand right before
/// every real `flutter build apk` + install -- not wired to a build
/// script, since this repo has no such automation yet, so keeping it
/// current is a manual discipline step, same category as running
/// `dart format` before considering a change done.
///
/// [kAppBuildStamp] is the short git commit hash the build was cut
/// from, plus the real date/time it was generated -- both are
/// independently checkable against `git log`/the clock, so a GM (or a
/// future session) can tell at a glance whether Settings is showing a
/// stale install or the build that was actually just pushed.
const kAppBuildStamp = '4801f87 -- 2026-08-22 00:23 CDT';
