/// Seed data for generating coaches -- players moved to
/// `player/generation/name_pools_by_country.dart`'s country-specific
/// pools (2026-08-10) once same-surname roster collisions made this flat
/// 44-name shared pool too small; coaches have no country concept, so
/// they kept this one. Purely invented — not drawn from any real coach's
/// name — combined at random, so any resemblance to a real person's full
/// name is coincidental.
const kFirstNames = <String>[
  'Aaliyah',
  'Sofia',
  'Emma',
  'Zoe',
  'Maya',
  'Chidinma',
  'Fatima',
  'Noor',
  'Priya',
  'Ingrid',
  'Freya',
  'Elena',
  'Camila',
  'Valentina',
  'Amara',
  'Kayla',
  'Brianna',
  'Destiny',
  'Jasmine',
  'Alexis',
  'Morgan',
  'Taylor',
  'Jordan',
  'Sydney',
  'Madison',
  'Olivia',
  'Ava',
  'Isabella',
  'Mia',
  'Charlotte',
  'Layla',
  'Nadia',
  'Yuki',
  'Hana',
  'Mei',
  'Aiko',
  'Anh',
  'Linh',
  'Thandiwe',
  'Zanele',
  'Ngozi',
  'Adaeze',
  'Keisha',
  'Simone',
  'Renee',
  'Danielle',
];

const kLastNames = <String>[
  'Okafor',
  'Adeyemi',
  'Mensah',
  'Osei',
  'Diallo',
  'Traore',
  'Kone',
  'Nakamura',
  'Watanabe',
  'Kim',
  'Park',
  'Nguyen',
  'Tran',
  'Singh',
  'Patel',
  'Sharma',
  'Kaur',
  'Rodriguez',
  'Martinez',
  'Garcia',
  'Hernandez',
  'Lopez',
  'Silva',
  'Costa',
  'Almeida',
  'Petrov',
  'Ivanova',
  'Kowalski',
  'Nowak',
  'Novak',
  'Andersson',
  'Larsen',
  'Johansson',
  'Murphy',
  'Kelly',
  "O'Brien",
  'Clarke',
  'Bennett',
  'Coleman',
  'Sanders',
  'Reed',
  'Hayes',
];
